spring:
  application:
    name: security
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: seulgi
    password: null
    driver-class-name: org.postgresql.Driver  #사용할 데이터베이스 드라이버의 클래스 이름
  jpa:
    hibernate:
      ddl-auto: create-drop #create-drop: #create-drop: 애플리케이션 시작 시 테이블을 생성하고 애플리케이션 종료 시 테이블을 삭제
    show-sql: true  #실행하는 SQL 쿼리를 콘솔에 표시
    properties:
      hibernate:
        format_sql: true  #SQL 쿼리를 포맷팅하여 읽기 쉽게 출력
    database: postgresql  #사용할 데이터베이스 종류
    database-platform: org.hibernate.dialect.PostgreSQLDialect  #사용할 데이터베이스의 SQL (어떤 데이터베이스를 사용하는지 알려주고, 그에 맞게 Hibernate가 SQL을 생성하도록 도와주는 설정)

server:
  port: 9091

jwt:
  sec-key: 4l9tJpX8XhCW1D7TPQDAxDRDXahJXerwND0tNi/JvC4=
